# Generated by Django 6.0.7 on 2026-07-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('candidate_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('candidate_links', models.JSONField(blank=True, default=list)),
                ('score', models.IntegerField(default=0)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('jd_match_score', models.IntegerField(blank=True, null=True)),
                ('skills_found', models.JSONField(blank=True, default=list)),
                ('skills_missing', models.JSONField(blank=True, default=list)),
                ('sections_present', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('suggested_roles', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
